### PR TITLE
Add/remove subscriptions to/from the dashboard

### PR DESCRIPTION
**Pull request by travisvalentine**
This is kinda a messy pull request so we'll handle it tomorrow.

Theoretically these tickets are closed since once a subscription is gone there is no feed to pull...

https://www.pivotaltracker.com/story/show/29736041
https://www.pivotaltracker.com/story/show/29736045

### CODE REVIEW

**Comment by athal7** [comment]
in trying to cherrypick only the commits you want, it looks like there is an error with how Item#post calls GithubEvent. I noticed this by trying to visit a user's feed. It seems that that capitalize.constantize method only works for one word models. We can choose either to change that method or change the model to one word. 

Please advise

**Comment by athal7** [comment]
for now I will write in a special clause for GithubEvent on this pull request, but this is not ideal, it will allow us to have a functional GithubEvent getter for the checkin though

**Comment by athal7** [comment]
I will send in another pull request to clean up the git history

**Comment by travisvalentine** [comment]
Hm the capitalize.constantize wasn't me

**Pull request closed without merging**
